"""
Django settings for haruum_gateway project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
from .credentials_setup import firebase_admin
from datetime import timedelta
from firebase_admin import auth, credentials, initialize_app
from pathlib import Path
import dj_database_url
import os

firebase_admin.setup_firebase_admin_credentials()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-kdp$qlc=09)l)ze38+e08p@)_@13f09$9*hr@#@fhvz@%2$ao#')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']
CORS_ALLOW_HEADERS = ['*']
CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt.token_blacklist',

    'main',
    'search',
    'order',
    'customer',
    'outlet',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'haruum_gateway.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'EXCEPTION_HANDLER': 'haruum_gateway.exception_config.custom_exception_handler',
}

WSGI_APPLICATION = 'haruum_gateway.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': dj_database_url.config(conn_max_age=600)
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = 'main.HaruumUser'

# Firebase Admin Configuration
FIREBASE_CREDENTIAL = credentials.Certificate(r'firebase-credentials.json')
FIREBASE_APP = initialize_app(credential=FIREBASE_CREDENTIAL)

OUTLET_APPLICATION_URL = f"http://{os.getenv('OUTLET_APPLICATION_URL')}"
OUTLET_REGISTRATION_URL = f'{OUTLET_APPLICATION_URL}/user/register/'
OUTLET_CREDENTIALS_URL = f'{OUTLET_APPLICATION_URL}/user/check-password/'
OUTLET_ALL_OUTLETS_URL = f'{OUTLET_APPLICATION_URL}/search/outlets/'
OUTLET_DETAIL_URL = f'{OUTLET_APPLICATION_URL}/user/data/'
OUTLET_SERVICES_URL = f'{OUTLET_APPLICATION_URL}/search/outlet/services/'
OUTLET_UPDATE_URL = f'{OUTLET_APPLICATION_URL}/user/update/'
OUTLET_UPDATE_SERVICE_URL = f'{OUTLET_APPLICATION_URL}/user/services-provided/update/'

CUSTOMER_APPLICATION_URL = f"http://{os.getenv('CUSTOMER_APPLICATION_URL')}"
CUSTOMER_REGISTRATION_URL = f'{CUSTOMER_APPLICATION_URL}/user/register/'
CUSTOMER_CREDENTIALS_URL = f'{CUSTOMER_APPLICATION_URL}/user/check-password/'
CUSTOMER_DETAILS_URL = f'{CUSTOMER_APPLICATION_URL}/user/data/'
CUSTOMER_UPDATE_ADDRESS_URL = f'{CUSTOMER_APPLICATION_URL}/user/update-address/'

ORDER_APPLICATION_URL = f"http://{os.getenv('ORDER_APPLICATION_URL')}"
ORDER_CREATION_URL = f'{ORDER_APPLICATION_URL}/order/create/'
ORDER_GET_ORDERS_OF_OUTLET_URL = f'{ORDER_APPLICATION_URL}/order/outlet-orders/'
ORDER_ALL_STATUS = f'{ORDER_APPLICATION_URL}/status/all'
ORDER_DETAILS_URL = f'{ORDER_APPLICATION_URL}/order/detail/'
ORDER_UPDATE_STATUS_URL = f'{ORDER_APPLICATION_URL}/status/update/'
ORDER_CUSTOMER_ACTIVE_URL = f'{ORDER_APPLICATION_URL}/order/customer-orders/active/'
ORDER_CUSTOMER_COMPLETED_URL = f'{ORDER_APPLICATION_URL}/order/customer-orders/completed/'
ORDER_SUBMIT_REVIEW_URL = f'{ORDER_APPLICATION_URL}/review/create/'
ORDER_GET_OUTLET_REVIEWS_URL = f'{ORDER_APPLICATION_URL}/review/outlet/'
ORDER_PAYMENT_METHODS_URL = f'{ORDER_APPLICATION_URL}/order/payment/all/'
